FROM maven:3.6-jdk-13 AS build
MAINTAINER maximilian schiedermeier
COPY src /usr/src/app/src
COPY pom.xml /usr/src/app
RUN mvn -f /usr/src/app/pom.xml clean package

## Discard Maven, run JAR file using JRE
FROM openjdk:8-jre-alpine

# copy the jar from the build stage, expose the required port and run it.
COPY --from=build /usr/src/app/target/Xox.jar /usr/app/Xox.jar
EXPOSE 4244
ENTRYPOINT ["java","-jar","/usr/app/Xox.jar"]

# allow debug if startup fails, with: docker run -it --entrypoint /bin/bash ls-xox -s
RUN apk add --no-cache bash coreutils grep sed
